baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'archie'

[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  GO_VERSION = "1.19"
