baseURL = 'https://thibaut7.io/'
languageCode = 'en-us'
title = 'thibaut7'
theme = 'archie'

[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = '0.143.1'
